// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1:string,arg2:string):Promise<any>;

export function ChatSiliconflow(arg1:string):Promise<void>;

export function CreateSession():Promise<any>;

export function Debug(arg1:string):Promise<void>;

export function Error(arg1:string):Promise<void>;

export function GetAPI():Promise<any>;

export function GetSessionList():Promise<any>;

export function GetTitle(arg1:string):Promise<any>;

export function HistoryChat(arg1:string):Promise<any>;

export function SetAPI(arg1:string):Promise<any>;
