// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chat} from '../models';

export function Chat(arg1:string):Promise<string>;

export function ChatSiliconflow(arg1:string):Promise<void>;

export function Debug(arg1:string):Promise<void>;

export function Error(arg1:string):Promise<void>;

export function HistoryChat(arg1:string):Promise<Array<chat.Conversation>>;
