// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function ChatSiliconflow(arg1) {
  return window['go']['main']['App']['ChatSiliconflow'](arg1);
}
