// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function ChatSiliconflow(arg1) {
  return window['go']['main']['App']['ChatSiliconflow'](arg1);
}

export function Debug(arg1) {
  return window['go']['main']['App']['Debug'](arg1);
}

export function Error(arg1) {
  return window['go']['main']['App']['Error'](arg1);
}

export function HistoryChat(arg1) {
  return window['go']['main']['App']['HistoryChat'](arg1);
}
